server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(CPjQ2bc4S9/UF8fIzIPuz3OS8nEhN3N8zPlW41n3x+luDA6eDPIzigTSpk5K/5uRQHlKwkVxHFwkONexkS20NuRuw1YPYt4DVs7RbINPUG6OKGTHuZjKHo/GwxywuwJ94RWawk/5wtvyfhsCUsxBz3DEnYZaJD1EFrtSTYC2nMY=)
    username: ENC(2wJ/ziTK7hTXLVQkRUOyfH8l6foq5bv2gbmWOjujKDevIRX31ipqQ6ohDRUR3aDz)
    password: ENC(k0GuX6G0TMPq9ALWxBXttpwdkyTA30ii3TQYutB5Zx6G2J0oQWc0XkMaxj2lzeyz)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

jwt:
  secretKey: ENC(AaB0O7vvslLcqyWfZ7P0X7cRdvsSmh4sUg1e6PfSy41r9vvxh6vpeMzY2zYAaXrxG2p7s/XCxkXF5nUxfwgObq03g4RB3fY3f9QAJPWkTmY=)
  accessTokenExpiration: 3000000000
  refreshTokenExpiration: 6000000000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor